name: deploy-auth

on:
  push:
    branches: 
      - master
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t behnamebrahimi/auth . # docker is installed on ubuntu-latest container
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD # we have to tell the container in github our credentials
        env: # secrets are not env variables. So in this section, we will introduce them as env variables.
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push behnamebrahimi/auth
      #- uses: digitalocean/action-doctl@v2
      #  with:
      #    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      #- run: doctl kubernetes cluster kubeconfig save ticketing
      #- run: kubectl rollout restart deployment auth-depl
